# Week 4: Fundamentals of Natural Language Processing

**1. Define Natural Language Processing (NLP) in your own words.**:
* Natural Language processing is a way of teaching the computer or machine to understand human language, and this goes beyound just understanding words in human languge but also understanding the content and sentiments in humnan language.


**2. List at least three real-world applications of NLP and explain their significance.**

*   Building Chatbots - Chatbots provides a conversational way to interact with humans.
*   Sentiment Analysis - Helps in understanding context and emotional tone in sentences
*   Machine Translation - Allowing machines to understand multiple languages, allowing us preserve our languages digitally



**3. Identify and explain two challenges that make NLP complex.**


*   Ambiguity in Language - Words and Sentences have different meaning depending on the context e.g when dealing with metaphors i.e "Time is a thief", or words with multiple meaning e.g Bank i.e. financial institution, or i.e. River Bank
*   Diversity in Human Language - Diffrent grammer and dialects that exist in human laguages makes it hard for machine to generalize languages, complicating NLP



**4. Extract the following patterns using regex:**

a) All email addresses from the text below:
“Contact us at support@company.com or sales@business.org. For more, email info@service.net.”

b) All words that end with "ing" from this sentence:
“NLP is amazing for cleaning and processing text while learning new
techniques.”:


In [1]:
import re

In [2]:
# a) Extract email addresses
text_emails = "Contact us at support@company.com or sales@business.org. For more, email info@service.net."
email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
emails = re.findall(email_pattern, text_emails)
print("Email addresses:", emails)

Email addresses: ['support@company.com', 'sales@business.org', 'info@service.net']


In [3]:
# b) Extract words ending with "ing"
text_ing = "NLP is amazing for cleaning and processing text while learning new techniques."
ing_pattern = r'\b\w+ing\b'
ing_words = re.findall(ing_pattern, text_ing)
print("Words ending with 'ing':", ing_words)

Words ending with 'ing': ['amazing', 'cleaning', 'processing', 'learning']


5. Write a Python program to clean the following text by:
“NLP makes AI smarter! But, sometimes, it’s challenging… Don’t you agree?”
* a) Removing all punctuation.
* b) Converting it to lowercase.
* c) Splitting it into words.

In [4]:
import string

# Original text
text = "NLP makes AI smarter! But, sometimes, it’s challenging… Don’t you agree?"

# a) Remove all punctuation
text_no_punct = text.translate(str.maketrans('', '', string.punctuation + "…’"))

# b) Convert to lowercase
text_lower = text_no_punct.lower()

# c) Split into words
words = text_lower.split()

# Display results
print("Cleaned words:", words)

Cleaned words: ['nlp', 'makes', 'ai', 'smarter', 'but', 'sometimes', 'its', 'challenging', 'dont', 'you', 'agree']


Applied Learning Assignments 2:
1. Text Cleaning Task
Apply text cleaning techniques to preprocess the following text:
"OMG!! NLP is soooo coool 🤩...!!! It costs $1000. Learn it now at https://3mtt.com 😎."
Refer to the course slide for more information

2. Tokenization Task
Perform both word-level and sentence-level tokenization on the given
text.
"Tokenization is the first step in NLP. It splits text into smaller pieces for
analysis."
* Use NLTK to perform word tokenization.
* Use NLTK to perform sentence tokenization

In [5]:
# Original text
text = "OMG!! NLP is soooo coool 🤩...!!! It costs $1000. Learn it now at https://3mtt.com 😎."

# Step 1: Convert to lowercase
text = text.lower()

# Step 2: Remove URLs
text = re.sub(r'https?://\S+', '', text)

# Step 3: Remove emojis (basic emoji pattern)
text = re.sub(r'[^\w\s.,!?$]', '', text)

# Step 4: Remove punctuation
text = re.sub(r'[^\w\s]', '', text)

# Step 5: Normalize elongated words (e.g., sooo -> so)
text = re.sub(r'([aeiou])\1{2,}', r'\1', text)

# Step 6: Remove extra whitespace
text = re.sub(r'\s+', ' ', text).strip()

# Final cleaned text
print("Cleaned Text:", text)

Cleaned Text: omg nlp is so col it costs 1000 learn it now at


3. Stemming and Lemmatization Task
Apply stemming and lemmatization techniques to a list of words:
["running", "flies", "studies", "easily", "studying", "better"]
* Use Porter Stemmer to perform stemming on the words.
* Use spaCy to perform lemmatization on the same words.


In [6]:
# 1. Porter Stemmer (from nltk)
import nltk
from nltk.stem import PorterStemmer

ps = PorterStemmer()

words = ["running", "flies", "studies", "easily", "studying", "better"]

stemmed_words = [ps.stem(word) for word in words]
print("Stemmed words:", stemmed_words)


# 2. Lemmatization using spaCy
import spacy

# Load English model
nlp = spacy.load("en_core_web_sm")

# Process the list of words as a single string
doc = nlp(" ".join(words))

lemmatized_words = [token.lemma_ for token in doc]
print("Lemmatized words:", lemmatized_words)

Stemmed words: ['run', 'fli', 'studi', 'easili', 'studi', 'better']
Lemmatized words: ['run', 'fly', 'study', 'easily', 'study', 'well']


Applied Learning Assignments 3:
1. Define a vocabulary of at least 5 unique words. Write Python code to
generate one-hot encoded vectors for your vocabulary.
2. Use the following sentences as your dataset:
– Write Python code to generate a Bag of Words representation for the
dataset using CountVectorizer.
– Write Python code to compute the TF-IDF representation using
TfidfVectorizer.
Week 4: Fundamentals of Natural Language Processing
* “The quick brown fox jumps over the lazy dog.”
* “The dog sleeps in the kernel”
Applied Learning Assignments 3:
3. Create a small dataset of at least 3 sentences related to animals.
Example: "The cat meows. The dog barks. The bird sings."
– Write Python code to:
* Train a Word2Vec model using gensim.
* Retrieve the embedding for the word "dog".
4. Load the pretrained GloVe model (glove-wiki-gigaword-50) using gensim.
– Write Python code to:
* Retrieve the embedding for the word "king".
* Find the 5 most similar words to "king".

In [7]:
#1

from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Define a small vocabulary
vocab = ['cat', 'dog', 'bird', 'lion', 'tiger']
vocab = np.array(vocab).reshape(-1, 1)

# Initialize and fit the encoder
encoder = OneHotEncoder()
one_hot = encoder.fit_transform(vocab)

# Print results
print(one_hot.toarray())

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
#2

from sklearn.feature_extraction.text import CountVectorizer

dataset = [
    "The quick brown fox jumps over the lazy dog.",
    "The dog sleeps in the kernel"
]

# Initialize and fit CountVectorizer
vectorizer = CountVectorizer()
bow = vectorizer.fit_transform(dataset)

# Show vocabulary and BoW matrix
print("Vocabulary:", vectorizer.vocabulary_)
print("BoW Matrix:\n", bow.toarray())

Vocabulary: {'the': 10, 'quick': 8, 'brown': 0, 'fox': 2, 'jumps': 4, 'over': 7, 'lazy': 6, 'dog': 1, 'sleeps': 9, 'in': 3, 'kernel': 5}
BoW Matrix:
 [[1 1 1 0 1 0 1 1 1 0 2]
 [0 1 0 1 0 1 0 0 0 1 2]]


In [9]:
#3

from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize and fit TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf = tfidf_vectorizer.fit_transform(dataset)

# Show vocabulary and TF-IDF matrix
print("Vocabulary:", tfidf_vectorizer.vocabulary_)
print("TF-IDF Matrix:\n", tfidf.toarray())

Vocabulary: {'the': 10, 'quick': 8, 'brown': 0, 'fox': 2, 'jumps': 4, 'over': 7, 'lazy': 6, 'dog': 1, 'sleeps': 9, 'in': 3, 'kernel': 5}
TF-IDF Matrix:
 [[0.342369   0.24359836 0.342369   0.         0.342369   0.
  0.342369   0.342369   0.342369   0.         0.48719673]
 [0.         0.30253071 0.         0.42519636 0.         0.42519636
  0.         0.         0.         0.42519636 0.60506143]]


In [10]:
from gensim.models import Word2Vec

sentences = [
    ["the", "cat", "meows"],
    ["the", "dog", "barks"],
    ["the", "bird", "sings"]
]

# Train Word2Vec model
model = Word2Vec(sentences, vector_size=50, window=3, min_count=1, workers=1)

# Get embedding for 'dog'
print("Embedding for 'dog':\n", model.wv['dog'])

Embedding for 'dog':
 [ 0.00018913  0.00615464 -0.01362529 -0.00275093  0.01533716  0.01469282
 -0.00734659  0.0052854  -0.01663426  0.01241097 -0.00927464 -0.00632821
  0.01862271  0.00174677  0.01498141 -0.01214813  0.01032101  0.01984565
 -0.01691478 -0.01027138 -0.01412967 -0.0097253  -0.00755713 -0.0170724
  0.01591121 -0.00968788  0.01684723  0.01052514 -0.01310005  0.00791574
  0.0109403  -0.01485307 -0.01481144 -0.00495046 -0.01725145 -0.00316314
 -0.00080687  0.00659937  0.00288376 -0.00176284 -0.01118812  0.00346073
 -0.00179474  0.01358738  0.00794718  0.00905894  0.00286861 -0.00539971
 -0.00873363 -0.00206415]
